---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(photobiology)
library(photobiologyWavebands)
library(ggspectra)
```


```{r}
setwd("not-inst")
```

```{r}
load(file = "G.Zuiko35mm2.spct.Rda")
plot(smooth_spct(normalize(clip_wl(G.Zuiko35mm2.spct, c(350,800))), 
                 method = "supsmu"), 
     annotations = c("color.guide")) +
       ggtitle("G.Zuiko 35mm f/2.8", subtitle = getWhenMeasured(G.Zuiko35mm2.spct))

```
```{r}
load(file = "Hanimex35mm.spct.Rda")
plot(smooth_spct(normalize(clip_wl(Hanimex35mm.spct, c(350,1000))), 
                 method = "supsmu"), 
     annotations = c("color.guide")) +
       ggtitle("Hanimex 35mm f/3.5", subtitle = getWhenMeasured(Hanimex35mm.spct))

```
```{r}
load(file = "soligor.spct.Rda")
plot(normalize(smooth_spct(clip_wl(soligor.spct, c(350,800)), 
                 method = "supsmu")), 
     annotations = c("color.guide")) +
       ggtitle("Soligor 35mm f/3.5", subtitle = getWhenMeasured(soligor.spct))

```

```{r}
load(file = "M.Zuiko17mm.spct.Rda")
plot(normalize(smooth_spct(clip_wl(M.Zuiko17mm.spct, c(350,800)), 
                 method = "supsmu")), 
     annotations = c("color.guide")) +
       ggtitle("M.Zuiko 17mm f/1.8", subtitle = getWhenMeasured(M.Zuiko17mm.spct))

```

```{r}
load(file = "UQG_Blue.spct.Rda")
plot(normalize(smooth_spct(clip_wl(UQG_Blue.spct, c(380,1000)), 
                 method = "supsmu")), 
     annotations = c("color.guide")) +
       ggtitle("UQG blue dichroic filter", 
               subtitle = getWhenMeasured(UQG_Blue.spct))

```