// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// MAYP11278_tail_correction
List MAYP11278_tail_correction(NumericVector w_length, NumericVector cts_second);
RcppExport SEXP ooacquire_MAYP11278_tail_correction(SEXP w_lengthSEXP, SEXP cts_secondSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type w_length(w_lengthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cts_second(cts_secondSEXP);
    rcpp_result_gen = Rcpp::wrap(MAYP11278_tail_correction(w_length, cts_second));
    return rcpp_result_gen;
END_RCPP
}
// MAYP112785_tail_correction
List MAYP112785_tail_correction(NumericVector w_length, NumericVector cts_second);
RcppExport SEXP ooacquire_MAYP112785_tail_correction(SEXP w_lengthSEXP, SEXP cts_secondSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type w_length(w_lengthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cts_second(cts_secondSEXP);
    rcpp_result_gen = Rcpp::wrap(MAYP112785_tail_correction(w_length, cts_second));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"ooacquire_MAYP11278_tail_correction", (DL_FUNC) &ooacquire_MAYP11278_tail_correction, 2},
    {"ooacquire_MAYP112785_tail_correction", (DL_FUNC) &ooacquire_MAYP112785_tail_correction, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ooacquire(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
